### ISSUE TITLE
Problem with multiple out in repeated runs

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#250] opened 2016-10-11 19:03 UTC
I am running into an issue which boils down to this MWE:

```
parameter: K = [2,3]

[work_1]
input: "1.txt", "2.txt", group_by = 'single', pattern = '{name}.{ext}'
output: expand_pattern('{_name}.out')
run:
  touch ${_output}

[work_2]

input: group_by = 'single', pattern = '{name}.{ext}', paired_with = ['K']
output: expand_pattern('{_name}.{_K}.out')
run: 
  touch ${_output}
```

If I run it for the first time it is fine,
```
sos run test.sos 
INFO: Executing work_1: 
INFO: input:    ['1.txt', '2.txt']
INFO: output:   ['1.out', '2.out']
INFO: Executing work_2: 
INFO: input:    ['1.out', '2.out']
INFO: output:   ['1.2.out', '2.3.out']
```

But if I run it again:
```
sos run test.sos 
INFO: Executing work_1: 
INFO: input:    ['1.txt', '2.txt']
INFO: Step work_1 (index=0) is ignored due to saved signature
INFO: Step work_1 (index=1) is ignored due to saved signature
INFO: output:   ['2.out']
INFO: Executing work_2: 
ERROR: Failed to process input statement group_by = 'single', pattern = '{name}.{ext}', paired_with = ['K']
: Length of variable K (length 2) should match the number of input files (length 1).
```

Apparently for the failed run, there is `output` from the first step `INFO: output:   ['2.out']` which is already not correct. Hope it is not a big issue to fix.

**Comment by BoPeng** [comment] 2016-10-11 20:10
The issue here is that the output is recovered from signature. There are two signatures that recovered `1.txt.out` and `2.txt.out`, but the complete `output` is not constructed from them. I am checking if there is an easy fix.

**Comment by BoPeng** [comment] 2016-10-11 20:26
Fixed. I however cannot run all tests because many tests are broken due to changes in preparation mode. Will check again after dust settles.

**Comment by gaow** [comment] 2016-10-11 20:32
Great, this example now works!

**Comment by BoPeng** [comment] 2016-10-11 22:30
The problem is more complicated and the fix was not appropriate. The root of the problem is `_output` changes so the first signature, when it comes to write, has incorrect `_output` (pointing to the second file). The patch tries to write the value when the signature was created (not written), but this is wrong because variables can change during execution, and we should saves values at the end of the execution.

The only proper solution is to differentiate the cases between concurrent and non-concurrent runs. For concurrent runs, we will have to use separate dictionaries for each incidence, and for non-concurrent runs we will have to make sure a signature is written before the next incidence starts... Both can be tricky.

**Comment by BoPeng** [comment] 2016-10-11 23:17
A proper fix has been committed.

**Closed by BoPeng** 2016-10-11 23:17 UTC
